### ISSUE TITLE
API3 version with OpenStreetMap

### ISSUE THREAD

**Issue by frspin** [SDRplay/dump1090#1]
Recent WEB interface of version of API3 with OpenStreetMap don't work on Ubuntu 18.04 64 bit.
On page load there is spinny.gif image and no map load.
Activating development tools of browser there are 3 errors messages:

ReferenceError: ol is not defined
ol3-layerswitcher.js:9:1
    <anonima> http://localhost:8080/ol3/ol3-layerswitcher.js:9

ReferenceError: ol is not defined
script.js:9:22
    <anonima> http://localhost:8080/script.js:9

TypeError: PlanesOrdered is undefined
script.js:876:25
    resortTable http://localhost:8080/script.js:876
    sortBy http://localhost:8080/script.js:901
    sortByAltitude http://localhost:8080/script.js:843
    initialize_map http://localhost:8080/script.js:362
    initialize http://localhost:8080/script.js:225
    jQuery 4
        i
        fireWith
        A
        c
Same errors with Firefox and Chrome browser

Regards

Franco Spinelli
IW2DHW
​

**Comment by dlaw** [comment]
I have the same errors on Debian 10.7.

The reason `ol` is not defined is because of the previous error:
```
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH    ol-3.17.1.js:1
```

This seems to indicate some issue with the HTTP server configuration.

Regards,
David

**Comment by dlaw** [comment]
`net_io.c` says "here we assume that the socket buffer is enough without doing any kind of userspace buffering".

The issue is that certain JS files are larger than the system socket buffer size:
```
$ du -b public_html/jquery/jquery-ui-1.11.4.min.js 
240427	public_html/jquery/jquery-ui-1.11.4.min.js

$ du -b public_html/ol3/ol-3.17.1.js 
495405	public_html/ol3/ol-3.17.1.js
```

The end of the file is truncated resulting in the reported content length mismatch. All the other errors are a result of these two files not loading.

**Comment by dlaw** [comment]
Workaround: pass `--net-buffer 3` as an additional argument to dump1090. This increases the TCP buffer size to 512 kilobytes, which is large enough for the giant jquery and ol scripts. (The default buffer size is 64 kilobytes.)

**Comment by edombek** [comment]
@dlaw  Does not help

```
127.0.0.1/:129          GET about:blank net::ERR_UNKNOWN_URL_SCHEME
127.0.0.1/:11          GET http://127.0.0.1:8080/ol3/ol-3.17.1.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
ol3-layerswitcher.js:9 Uncaught ReferenceError: ol is not defined
    at ol3-layerswitcher.js:9:1
(anonymous) @ ol3-layerswitcher.js:9
script.js:6 Uncaught ReferenceError: ol is not defined
    at script.js:6:22
(anonymous) @ script.js:6
127.0.0.1/:219          GET about:blank net::ERR_UNKNOWN_URL_SCHEME
script.js:873 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at resortTable (script.js:873:43)
    at sortBy (script.js:898:9)
    at sortByAltitude (script.js:840:29)
    at initialize_map (script.js:359:17)
    at Object.<anonymous> (script.js:222:25)
    at i (jquery-3.0.0.min.js:2:27623)
    at Object.fireWith [as resolveWith] (jquery-3.0.0.min.js:2:28389)
    at A (jquery-3.0.0.min.js:4:13816)
    at XMLHttpRequest.<anonymous> (jquery-3.0.0.min.js:4:16102)
resortTable @ script.js:873
sortBy @ script.js:898
sortByAltitude @ script.js:840
initialize_map @ script.js:359
(anonymous) @ script.js:222
i @ jquery-3.0.0.min.js:2
fireWith @ jquery-3.0.0.min.js:2
A @ jquery-3.0.0.min.js:4
(anonymous) @ jquery-3.0.0.min.js:4
load (async)
send @ jquery-3.0.0.min.js:4
ajax @ jquery-3.0.0.min.js:4
initialize @ script.js:202
onload @ (index):31
```
