### ISSUE TITLE
lot of errors like "multiple definition of"

### ISSUE THREAD

**Issue by Dieter9** [SDRplay/dump1090#2]
I tried to compile the api3 branch on my Arch Linux System, but got a lot of errors like this:

```
gcc -g -o dump1090 dump1090.o anet.o interactive.o mode_ac.o mode_s.o net_io.o crc.o demod_2000.o demod_2400.o demod_8000.o stats.o cpr.o icao_filter.o track.o util.o convert.o dump1090.h -L./ -lsdrplay_api -lpthread -lm -lrtlsdr  -lrt `pkg-config --libs librtlsdr`  
/usr/bin/ld: interactive.o:/home/my/src/dump1090-api3/dump1090.h:403: multiple definition of `Modes'; dump1090.o:/home/my/src/dump1090-api3/dump1090.h:403: first defined here
/usr/bin/ld: interactive.o:/home/my/src/dump1090-api3/dump1090.h:411: multiple definition of `slaveAttached'; dump1090.o:/home/my/src/dump1090-api3/dump1090.h:411: first defined here
/usr/bin/ld: interactive.o:/home/my/src/dump1090-api3/dump1090.h:410: multiple definition of `slaveUninitialised'; dump1090.o:/home/my/src/dump1090-api3/dump1090.h:410: first defined here
/usr/bin/ld: interactive.o:/home/my/src/dump1090-api3/dump1090.h:410: multiple definition of `masterInitialised'; dump1090.o:/home/my/src/dump1090-api3/dump1090.h:410: first defined here
```

I have searching in the internet and tried a lot but was not able to fix the Problem.

**Comment by srs4511351** [comment]
Please see my post on issue API3 version compile error #6
It tries to explain the error, but we need a programmer to fix it.

----Steve

**Comment by srs4511351** [comment]
If you have a Raspberry Pi or an older OS that you can boot to, see  API3 version compile error #6 
I managed to get it to work.

----Steve

**Comment by Dieter9** [comment]
Thank you for the information, but I think the problem has to be fixed in the source code by the owner.

**Comment by srs4511351** [comment]
How did you do it? The source code branch cloned by this command hasn't  been changed in 2 years.
git clone https://github.com/SDRplay/dump1090 -b api3

Recently, I had the same multiple definition errors when compiling this code with gcc 10.2.1
The older version in Debian buster did not have the problem.

----Steve

**Comment by SDRplay** [comment]
Sorry for the delay on sorting this...

The repo has been cleaned up and now the master branch supports API3 and should build correctly. The README.md has been updated with better instructions and the Makefile has some additional comments.

Best regards,

Andy
