### ISSUE TITLE
 install via apt-get not working 

### ISSUE THREAD

**Issue by messschuh** [SDRplay/dump1090#3]
wget https://github.com/mutability/mutability-repo/releases/download/v0.1.0/mutability-repo_0.1.0_armhf.deb
--2021-05-31 22:53:49--  https://github.com/mutability/mutability-repo/releases/download/v0.1.0/mutability-repo_0.1.0_armhf.deb
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-31 22:53:49 ERROR 404: Not Found.

**Comment by Konradrundfunk** [comment]
Get the same error seams that the ARM version is still up. Furthermore I see no real reason why they deleted the realease from github.

**Comment by SDRplay** [comment]
There is, and never has been, a way to get this build via apt-get - the readme is just the one that was in the original repository that this was forked from. If you want the ARM binary without building this, the easiest thing is to get our image https://www.sdrplay.com/raspberry-pi-images
