### ISSUE TITLE
Freq option doesn't seem to work

### ISSUE THREAD

**Issue by marrem** [SDRplay/dump1090#9]
No matter what I enter after --freq option, even e.g. 200MHz (on which no ADS-B is active) --freq 200000000, it still receives a lot of traffic. It shows the same flights as without the option (using 1090MHz). It looks like the option has no effect.

Using commit: master e320bd526c7abef33a69505bf12beefddf294dd4

Using SDRPlay RSPdx:

$ SoapySDRUtil --find
######################################################
######################################################

Found device 0
  driver = remote
  label = SDRplay Dev0 RSPdx 210508C845
  remote = tcp://192.168.10.99:55132
  remote:driver = sdrplay
  serial = 210508C845

Found device 1
  driver = sdrplay
  label = SDRplay Dev0 RSPdx 210508C845
  serial = 210508C845

**Comment by SDRplay** [comment]
--freq is ignored and 1090 MHz is always used for this version of dump1090. You can modify the code to use the frequency specified on the command line if you prefer.
